# guilde infos
guildeInfos:
    path: /guilde/infos
    defaults: { _controller: AppBundle:Default:guildeInfos}

# guilde members
guildeMembers:
    path: /guilde/members
    defaults: { _controller: AppBundle:Default:getGuildeMembers}


# dev
dev:
    path: /dev
    defaults: { _controller: AppBundle:Default:dev}